local NO_JOINT_BITS = 0
local STRING_LOAD_GAME = "load_game"
local INV_ROT_Y = 1

PICKUP_DATA = {}

local COL = {
    OBJECT_ID = 1,
    YOFFSET = 2,
    SCALE = 3,
    ROTATION = 4,
    MENUACTIONS = 5,
    DISPLAY_NAME = 6,
    MESHBITS = 7,
    ORIENTATION = 8,
	TYPE = 9,
	COMBINE = 10,
	RING = 11,
}

PICKUP_DATA.TYPE = {
    WEAPON = 1,
    AMMO = 2,
    MEDIPACK = 3,
    TOOL = 4,
    PUZZLE = 5,
    WATERSKIN = 6,
    SAVE = 7
}

PICKUP_DATA.RING = {
	PUZZLE = 1,
    MAIN = 2,
	OPTIONS = 3,
	COMBINE = 4,
	AMMO = 5
}

PICKUP_DATA.RING_CENTER = {
    [PICKUP_DATA.RING.PUZZLE] = Vec3(0,-800,1024),
    [PICKUP_DATA.RING.MAIN] = Vec3(0,200,1024),
    [PICKUP_DATA.RING.OPTIONS] = Vec3(0,1200,1024),
    [PICKUP_DATA.RING.COMBINE] = Vec3(0,300,1024),
    [PICKUP_DATA.RING.AMMO] = Vec3(0,300,1024)
}

PICKUP_DATA.HEALTH_MAX = 1000

PICKUP_DATA.constants = {
	-- Weapons
	{ TEN.Objects.ObjID.PISTOLS_ITEM, 6, 0.5, Rotation(244.0, 90.0, 276.0), ItemAction.EQUIP | ItemAction.CHOOSE_AMMO_PISTOLS, "pistols", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON, false, PICKUP_DATA.RING.MAIN },
	{ TEN.Objects.ObjID.UZI_ITEM, -4, 0.5, Rotation(135.0, -90.0, 90.0), ItemAction.EQUIP | ItemAction.CHOOSE_AMMO_UZI, "uzis" , NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON, false, PICKUP_DATA.RING.MAIN },
	{ TEN.Objects.ObjID.SHOTGUN_ITEM, -6, 0.8, Rotation(270.0, -20.0, 45), ItemAction.EQUIP | ItemAction.CHOOSE_AMMO_SHOTGUN, "shotgun", 0x01, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON, false, PICKUP_DATA.RING.MAIN },
	{ TEN.Objects.ObjID.REVOLVER_ITEM, 0, 0.5, Rotation(60.0, -90.0, 85.0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_REVOLVER, "revolver" , 0x01, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON, true, PICKUP_DATA.RING.MAIN },
	--{ TEN.Objects.ObjID.REVOLVER_ITEM, 0, 0.5, Rotation(60.0, 90.0, 85.0), ItemAction.EQUIP | ItemAction.SEPARATE | ItemAction.CHOOSE_AMMO_REVOLVER, "revolver_lasersight", 0x0B, INV_ROT_Y },
	{ TEN.Objects.ObjID.CROSSBOW_ITEM, 0, 0.5, Rotation(33.0, -90.0, 0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_CROSSBOW, "crossbow", 0x01, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON, true, PICKUP_DATA.RING.MAIN},
	--{ TEN.Objects.ObjID.CROSSBOW_ITEM, 0, 0.5, Rotation(33.0, -90.0, 0), ItemAction.EQUIP | ItemAction.SEPARATE | ItemAction.CHOOSE_AMMO_CROSSBOW, "crossbow_lasersight", 0x03, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON},
	{ TEN.Objects.ObjID.HK_ITEM, 0, 0.5, Rotation(280.0, 0, 0), ItemAction.EQUIP | ItemAction.COMBINE | ItemAction.CHOOSE_AMMO_HK, "hk", 0x01, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON, true, PICKUP_DATA.RING.MAIN},
	--{ TEN.Objects.ObjID.HK_ITEM, 0, 0.5, Rotation(280.0, -45.0, 0), ItemAction.EQUIP | ItemAction.SEPARATE | ItemAction.CHOOSE_AMMO_HK, "hk_lasersight", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON},
	--{ TEN.Objects.ObjID.HK_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 0), ItemAction.USE, "hk_rapid_mode", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON},
	--{ TEN.Objects.ObjID.HK_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 0), ItemAction.USE, "hk_burst_mode", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON},
	--{ TEN.Objects.ObjID.HK_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 0), ItemAction.USE, "hk_sniper_mode", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON},
	{ TEN.Objects.ObjID.GRENADE_GUN_ITEM, 0, 0.5, Rotation(0, 90.0, 65), ItemAction.EQUIP | ItemAction.CHOOSE_AMMO_GRENADEGUN, "grenade_launcher", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.HARPOON_ITEM, 0, 0.5, Rotation(-65.0, 0, -20.0), ItemAction.EQUIP | ItemAction.CHOOSE_AMMO_HARPOON, "harpoon_gun", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.ROCKET_LAUNCHER_ITEM, 0, 0.5, Rotation(80.0, 180.0, 0), ItemAction.EQUIP | ItemAction.CHOOSE_AMMO_ROCKET, "rocket_launcher", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WEAPON, false, PICKUP_DATA.RING.MAIN},

	{ TEN.Objects.ObjID.PISTOLS_AMMO_ITEM, 4, 0.5, Rotation(0, 0, 0), ItemAction.USE, "pistol_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.UZI_AMMO_ITEM, 5, 0.5, Rotation(29.5, 0, 0), ItemAction.USE, "uzi_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.SHOTGUN_AMMO1_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "shotgun_normal_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.SHOTGUN_AMMO2_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "shotgun_wideshot_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.REVOLVER_AMMO_ITEM, 0, 0.5, Rotation(-16.0, 180.0, 0), ItemAction.USE, "revolver_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.CROSSBOW_AMMO1_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "crossbow_normal_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.CROSSBOW_AMMO2_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "crossbow_poison_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.CROSSBOW_AMMO3_ITEM, 0, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "crossbow_explosive_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.HK_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 0), ItemAction.USE, "hk_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.GRENADE_AMMO1_ITEM, 3, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "grenade_launcher_normal_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.GRENADE_AMMO2_ITEM, 3, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "grenade_launcher_super_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.GRENADE_AMMO3_ITEM, 3, 0.5, Rotation(0, -90.0, 0), ItemAction.USE, "grenade_launcher_flash_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.HARPOON_AMMO_ITEM, 3, 0.5, Rotation(15.0, 0, 0), ItemAction.USE, "harpoon_gun_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.ROCKET_LAUNCHER_AMMO_ITEM, 3, 0.5, Rotation(0, 90.0, 15.0), ItemAction.USE, "rocket_launcher_ammo", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.AMMO, false, PICKUP_DATA.RING.MAIN},

	-- Miscellaneous
	{ TEN.Objects.ObjID.LASERSIGHT_ITEM, 2, 0.5, Rotation(10.0, 90.0, 0), ItemAction.COMBINE, "lasersight", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.SILENCER_ITEM, 1, 0.5, Rotation(10.0, 0, 0), ItemAction.COMBINE, "silencer", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.BIGMEDI_ITEM, 2, 0.7, Rotation(0, 180.0, 0), ItemAction.USE, "large_medipack", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.MEDIPACK, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.SMALLMEDI_ITEM, 0, 0.7, Rotation(112.0, 180.0, 0), ItemAction.USE, "small_medipack", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.MEDIPACK, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.BINOCULARS_ITEM, -1, 0.5, Rotation(10.0, 180.0, 0), ItemAction.USE, "binoculars", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.FLARE_INV_ITEM, 52, 0.8, Rotation(0, 0, 0), ItemAction.USE, "flares", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, false, PICKUP_DATA.RING.MAIN},
	{ TEN.Objects.ObjID.STOPWATCH_ITEM, 2, 0.8, Rotation(0, 180, 0), ItemAction.STATISTICS, "statistics", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PC_LOAD_INV_ITEM, 52, 0.3, Rotation(0, 180.0, 0), ItemAction.LOAD, "load_game", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.SAVE, false, PICKUP_DATA.RING.OPTIONS},
	{ TEN.Objects.ObjID.PC_SAVE_INV_ITEM, 52, 0.3, Rotation(0, 180.0, 0), ItemAction.SAVE, "save_game", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.SAVE, false, PICKUP_DATA.RING.OPTIONS},
	{ TEN.Objects.ObjID.BURNING_TORCH_ITEM, 14, 0.5, Rotation(90.0, 0, 0), ItemAction.USE, "torch", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.CROWBAR_ITEM, 4, 0.5, Rotation(90.0, 0, 0), ItemAction.USE, "crowbar", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.DIARY_ITEM, 0, 0.3, Rotation(0, 180.0, 0), ItemAction.USE, "diary", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.COMPASS_ITEM, -14, 0.5, Rotation(90.0, 0, 0), ItemAction.EXAMINE, "load_game", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.CLOCKWORK_BEETLE, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE, "mechanical_scarab", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.CLOCKWORK_BEETLE_COMBO1, 18, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, "mechanical_scarab_1", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.CLOCKWORK_BEETLE_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, "mechanical_scarab_2", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN1_EMPTY, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_small_empty", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN1_1, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_small_1l", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN1_2, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_small_2l", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN1_3, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_small_3l", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN2_EMPTY, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_empty", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN2_1, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_1l", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN2_2, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_2l", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN2_3, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_3l", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN2_4, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_4l", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.WATERSKIN2_5, 2, 0.5, Rotation(285.0, 0, 0), ItemAction.USE | ItemAction.COMBINE, "waterskin_large_5l", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.WATERSKIN, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.DIARY_OPEN, 0, 0.9, Rotation(0, 90.0, 0), ItemAction.USE, "load_game", NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.TOOL, false, PICKUP_DATA.RING.PUZZLE},

	-- Puzzles
	{ TEN.Objects.ObjID.PUZZLE_ITEM1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM2, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM3, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM4, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM5, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM6, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM7, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM8, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM9, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM10, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM11, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM12, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM13, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM14, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM15, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM16, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},

	-- Puzzle combos
	{ TEN.Objects.ObjID.PUZZLE_ITEM1_COMBO1, 18, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM1_COMBO2, 18, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM2_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM2_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM3_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM3_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM4_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM4_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM5_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM5_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM6_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM6_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM7_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM7_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM8_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM8_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM9_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM9_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM10_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM10_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM11_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM11_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM12_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM12_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM13_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM13_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM14_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM14_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM15_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM15_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM16_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PUZZLE_ITEM16_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},

	-- Keys
	{ TEN.Objects.ObjID.KEY_ITEM1, 14, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM3, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM4, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM5, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM6, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM7, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM8, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM9, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM10, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM11, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM12, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM13, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM14, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM15, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM16, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},

	-- Key combos
	{ TEN.Objects.ObjID.KEY_ITEM1_COMBO1, 18, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM1_COMBO2, 18, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM2_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM2_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM3_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM3_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM4_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM4_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM5_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM5_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM6_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM6_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM7_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM7_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM8_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM8_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM9_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM9_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM10_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM10_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM11_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM11_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM12_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM12_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM13_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM13_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM14_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM14_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM15_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM15_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM16_COMBO1, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.KEY_ITEM16_COMBO2, 8, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},

	-- Pickups
	{ TEN.Objects.ObjID.PICKUP_ITEM1, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM2, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM3, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM4, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM5, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM6, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM7, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM8, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM9, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM10, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM11, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM12, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM13, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM14, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM15, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM16, 8, 0.5, Rotation(0, 0, 0), ItemAction.USE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},

	-- Pickup combos
	{ TEN.Objects.ObjID.PICKUP_ITEM1_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM1_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM2_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM2_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM3_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM3_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM4_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM4_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM5_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM5_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM6_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM6_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM7_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM7_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM8_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM8_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM9_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM9_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM10_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM10_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM11_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM11_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM12_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM12_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM13_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM13_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM14_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM14_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM15_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM15_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM16_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.PICKUP_ITEM16_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},

	-- Examines
	{ TEN.Objects.ObjID.EXAMINE1, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE2, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE3, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE4, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE5, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE6, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE7, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE8, 14, 0.5, Rotation(0, 0, 0), ItemAction.EXAMINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, false, PICKUP_DATA.RING.PUZZLE},

	-- Examines combos
	{ TEN.Objects.ObjID.EXAMINE1_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE1_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE2_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE2_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE3_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE3_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE4_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE4_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE5_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE5_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE6_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE6_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE7_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE7_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE8_COMBO1, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
	{ TEN.Objects.ObjID.EXAMINE8_COMBO2, 14, 0.5, Rotation(0, 0, 0), ItemAction.COMBINE, STRING_LOAD_GAME, NO_JOINT_BITS, INV_ROT_Y, PICKUP_DATA.TYPE.PUZZLE, true, PICKUP_DATA.RING.PUZZLE},
}

PICKUP_DATA.combineTable =
{
	{ TEN.Objects.ObjID.REVOLVER_ITEM, TEN.Objects.ObjID.LASERSIGHT_ITEM, TEN.Objects.ObjID.REVOLVER_ITEM },
	{ TEN.Objects.ObjID.CROSSBOW_ITEM, TEN.Objects.ObjID.LASERSIGHT_ITEM, TEN.Objects.ObjID.CROSSBOW_ITEM },
	{ TEN.Objects.ObjID.HK_ITEM, TEN.Objects.ObjID.LASERSIGHT_ITEM, TEN.Objects.ObjID.HK_ITEM },
	{ TEN.Objects.ObjID.PUZZLE_ITEM1_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM1_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM1 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM2_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM2_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM2 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM3_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM3_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM3 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM4_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM4_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM4 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM5_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM5_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM5 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM6_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM6_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM6 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM7_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM7_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM7 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM8_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM8_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM8 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM9_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM9_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM9 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM10_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM10_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM10 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM11_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM11_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM11 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM12_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM12_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM12 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM13_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM13_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM13 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM14_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM14_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM14 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM15_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM15_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM15 },
	{ TEN.Objects.ObjID.PUZZLE_ITEM16_COMBO1, TEN.Objects.ObjID.PUZZLE_ITEM16_COMBO2, TEN.Objects.ObjID.PUZZLE_ITEM16 },
	{ TEN.Objects.ObjID.KEY_ITEM1_COMBO1, TEN.Objects.ObjID.KEY_ITEM1_COMBO2, TEN.Objects.ObjID.KEY_ITEM1 },
	{ TEN.Objects.ObjID.KEY_ITEM2_COMBO1, TEN.Objects.ObjID.KEY_ITEM2_COMBO2, TEN.Objects.ObjID.KEY_ITEM2 },
	{ TEN.Objects.ObjID.KEY_ITEM3_COMBO1, TEN.Objects.ObjID.KEY_ITEM3_COMBO2, TEN.Objects.ObjID.KEY_ITEM3 },
	{ TEN.Objects.ObjID.KEY_ITEM4_COMBO1, TEN.Objects.ObjID.KEY_ITEM4_COMBO2, TEN.Objects.ObjID.KEY_ITEM4 },
	{ TEN.Objects.ObjID.KEY_ITEM5_COMBO1, TEN.Objects.ObjID.KEY_ITEM5_COMBO2, TEN.Objects.ObjID.KEY_ITEM5 },
	{ TEN.Objects.ObjID.KEY_ITEM6_COMBO1, TEN.Objects.ObjID.KEY_ITEM6_COMBO2, TEN.Objects.ObjID.KEY_ITEM6 },
	{ TEN.Objects.ObjID.KEY_ITEM7_COMBO1, TEN.Objects.ObjID.KEY_ITEM7_COMBO2, TEN.Objects.ObjID.KEY_ITEM7 },
	{ TEN.Objects.ObjID.KEY_ITEM8_COMBO1, TEN.Objects.ObjID.KEY_ITEM8_COMBO2, TEN.Objects.ObjID.KEY_ITEM8 },
	{ TEN.Objects.ObjID.KEY_ITEM9_COMBO1, TEN.Objects.ObjID.KEY_ITEM9_COMBO2, TEN.Objects.ObjID.KEY_ITEM9 },
	{ TEN.Objects.ObjID.KEY_ITEM10_COMBO1, TEN.Objects.ObjID.KEY_ITEM10_COMBO2, TEN.Objects.ObjID.KEY_ITEM10 },
	{ TEN.Objects.ObjID.KEY_ITEM11_COMBO1, TEN.Objects.ObjID.KEY_ITEM11_COMBO2, TEN.Objects.ObjID.KEY_ITEM11 },
	{ TEN.Objects.ObjID.KEY_ITEM12_COMBO1, TEN.Objects.ObjID.KEY_ITEM12_COMBO2, TEN.Objects.ObjID.KEY_ITEM12 },
	{ TEN.Objects.ObjID.KEY_ITEM13_COMBO1, TEN.Objects.ObjID.KEY_ITEM13_COMBO2, TEN.Objects.ObjID.KEY_ITEM13 },
	{ TEN.Objects.ObjID.KEY_ITEM14_COMBO1, TEN.Objects.ObjID.KEY_ITEM14_COMBO2, TEN.Objects.ObjID.KEY_ITEM14 },
	{ TEN.Objects.ObjID.KEY_ITEM15_COMBO1, TEN.Objects.ObjID.KEY_ITEM15_COMBO2, TEN.Objects.ObjID.KEY_ITEM15 },
	{ TEN.Objects.ObjID.KEY_ITEM16_COMBO1, TEN.Objects.ObjID.KEY_ITEM16_COMBO2, TEN.Objects.ObjID.KEY_ITEM16 },
	{ TEN.Objects.ObjID.PICKUP_ITEM1_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM1_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM1 },
	{ TEN.Objects.ObjID.PICKUP_ITEM2_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM2_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM2 },
	{ TEN.Objects.ObjID.PICKUP_ITEM3_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM3_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM3 },
	{ TEN.Objects.ObjID.PICKUP_ITEM4_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM4_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM4 },
	{ TEN.Objects.ObjID.PICKUP_ITEM5_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM5_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM5 },
	{ TEN.Objects.ObjID.PICKUP_ITEM6_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM6_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM6 },
	{ TEN.Objects.ObjID.PICKUP_ITEM7_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM7_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM7 },
	{ TEN.Objects.ObjID.PICKUP_ITEM8_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM8_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM8 },
	{ TEN.Objects.ObjID.PICKUP_ITEM9_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM9_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM9 },
	{ TEN.Objects.ObjID.PICKUP_ITEM10_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM10_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM10 },
	{ TEN.Objects.ObjID.PICKUP_ITEM11_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM11_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM11 },
	{ TEN.Objects.ObjID.PICKUP_ITEM12_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM12_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM12 },
	{ TEN.Objects.ObjID.PICKUP_ITEM13_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM13_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM13 },
	{ TEN.Objects.ObjID.PICKUP_ITEM14_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM14_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM14 },
	{ TEN.Objects.ObjID.PICKUP_ITEM15_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM15_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM15 },
	{ TEN.Objects.ObjID.PICKUP_ITEM16_COMBO1, TEN.Objects.ObjID.PICKUP_ITEM16_COMBO2, TEN.Objects.ObjID.PICKUP_ITEM16 },
	{ TEN.Objects.ObjID.EXAMINE1_COMBO1, TEN.Objects.ObjID.EXAMINE1_COMBO2, TEN.Objects.ObjID.EXAMINE1 },
	{ TEN.Objects.ObjID.EXAMINE2_COMBO1, TEN.Objects.ObjID.EXAMINE2_COMBO2, TEN.Objects.ObjID.EXAMINE2 },
	{ TEN.Objects.ObjID.EXAMINE3_COMBO1, TEN.Objects.ObjID.EXAMINE3_COMBO2, TEN.Objects.ObjID.EXAMINE3 },
	{ TEN.Objects.ObjID.EXAMINE4_COMBO1, TEN.Objects.ObjID.EXAMINE4_COMBO2, TEN.Objects.ObjID.EXAMINE4 },
	{ TEN.Objects.ObjID.EXAMINE5_COMBO1, TEN.Objects.ObjID.EXAMINE5_COMBO2, TEN.Objects.ObjID.EXAMINE5 },
	{ TEN.Objects.ObjID.EXAMINE6_COMBO1, TEN.Objects.ObjID.EXAMINE6_COMBO2, TEN.Objects.ObjID.EXAMINE6 },
	{ TEN.Objects.ObjID.EXAMINE7_COMBO1, TEN.Objects.ObjID.EXAMINE7_COMBO2, TEN.Objects.ObjID.EXAMINE7 },
	{ TEN.Objects.ObjID.EXAMINE8_COMBO1, TEN.Objects.ObjID.EXAMINE8_COMBO2, TEN.Objects.ObjID.EXAMINE8 },
	{ TEN.Objects.ObjID.CLOCKWORK_BEETLE_COMBO1, TEN.Objects.ObjID.CLOCKWORK_BEETLE_COMBO2, TEN.Objects.ObjID.CLOCKWORK_BEETLE },
}

--Structure for weapon data. TEN Weapon type constant, underwater equip allowed, equip while crawling allowed
PICKUP_DATA.WEAPON_SET = {
    [TEN.Objects.ObjID.PISTOLS_ITEM] = {slot = TEN.Objects.WeaponType.PISTOLS, underwater = false, crawl = true}, 
    [TEN.Objects.ObjID.UZI_ITEM] = {slot = TEN.Objects.WeaponType.UZIS, underwater = false, crawl = true}, 
    [TEN.Objects.ObjID.SHOTGUN_ITEM] = {slot = TEN.Objects.WeaponType.SHOTGUN, underwater = false, crawl = false},
    [TEN.Objects.ObjID.REVOLVER_ITEM] = {slot = TEN.Objects.WeaponType.REVOLVER, underwater = false, crawl = true},
    [TEN.Objects.ObjID.CROSSBOW_ITEM] = {slot = TEN.Objects.WeaponType.CROSSBOW, underwater = false, crawl = false},
    [TEN.Objects.ObjID.HK_ITEM] = {slot = TEN.Objects.WeaponType.HK, underwater = false, crawl = false},
    [TEN.Objects.ObjID.GRENADE_GUN_ITEM] = {slot = TEN.Objects.WeaponType.GRENADE_LAUNCHER, underwater = false, crawl = false},
    [TEN.Objects.ObjID.HARPOON_ITEM] = {slot = TEN.Objects.WeaponType.HARPOON_GUN, underwater = true, crawl = false},
    [TEN.Objects.ObjID.ROCKET_LAUNCHER_ITEM] = {slot = TEN.Objects.WeaponType.ROCKET_LAUNCHER, underwater = false, crawl = false},
    [TEN.Objects.ObjID.FLARE_INV_ITEM] = {slot = TEN.Objects.WeaponType.FLARE, underwater = true, crawl = true}
}

PICKUP_DATA.WEAPON_LASERSIGHT_DATA = {
    [TEN.Objects.ObjID.REVOLVER_ITEM] = {MESHBITS = 0x0B, NAME = "revolver_lasersight", FLAGS = ItemAction.EQUIP | ItemAction.SEPARATE | ItemAction.CHOOSE_AMMO_REVOLVER},                            
    [TEN.Objects.ObjID.CROSSBOW_ITEM] = {MESHBITS = 0x03, NAME = "crossbow_lasersight", FLAGS = ItemAction.EQUIP | ItemAction.SEPARATE | ItemAction.CHOOSE_AMMO_CROSSBOW},                          
    [TEN.Objects.ObjID.HK_ITEM]       = {MESHBITS = 0, NAME = "hk_lasersight", FLAGS = ItemAction.EQUIP | ItemAction.SEPARATE | ItemAction.CHOOSE_AMMO_HK},
    }

PICKUP_DATA.WEAPON_AMMO_LOOKUP = {
    [TEN.Objects.ObjID.PISTOLS_ITEM] = {TEN.Objects.ObjID.PISTOLS_AMMO_ITEM},
    [TEN.Objects.ObjID.UZI_ITEM] = {TEN.Objects.ObjID.UZI_AMMO_ITEM},
    [TEN.Objects.ObjID.SHOTGUN_ITEM] = {TEN.Objects.ObjID.SHOTGUN_AMMO1_ITEM, TEN.Objects.ObjID.SHOTGUN_AMMO2_ITEM},
    [TEN.Objects.ObjID.REVOLVER_ITEM] = {TEN.Objects.ObjID.REVOLVER_AMMO_ITEM},
    [TEN.Objects.ObjID.CROSSBOW_ITEM] = {TEN.Objects.ObjID.CROSSBOW_AMMO1_ITEM, TEN.Objects.ObjID.CROSSBOW_AMMO2_ITEM, TEN.Objects.ObjID.CROSSBOW_AMMO3_ITEM},
    [TEN.Objects.ObjID.HK_ITEM] = {TEN.Objects.ObjID.HK_AMMO_ITEM},
    [TEN.Objects.ObjID.GRENADE_GUN_ITEM] = {TEN.Objects.ObjID.GRENADE_AMMO1_ITEM, TEN.Objects.ObjID.GRENADE_AMMO2_ITEM, TEN.Objects.ObjID.GRENADE_AMMO3_ITEM},
    [TEN.Objects.ObjID.HARPOON_ITEM] = {TEN.Objects.ObjID.HARPOON_AMMO_ITEM},
    [TEN.Objects.ObjID.ROCKET_LAUNCHER_ITEM] = {TEN.Objects.ObjID.ROCKET_LAUNCHER_AMMO_ITEM}
}

PICKUP_DATA.WEAPON_MODE_LOOKUP = {
    {weapon = TEN.Objects.ObjID.HK_ITEM, string = "hk_rapid_mode"},
    {weapon = TEN.Objects.ObjID.HK_ITEM, string = "hk_burst_mode"},
    {weapon = TEN.Objects.ObjID.HK_ITEM, string = "hk_sniper_mode"},
    }

PICKUP_DATA.AMMO_SET = {
    [TEN.Objects.ObjID.PISTOLS_AMMO_ITEM] = {slot = TEN.Objects.AmmoType.PISTOLS, weapon = TEN.Objects.ObjID.PISTOLS_ITEM}, 
    [TEN.Objects.ObjID.UZI_AMMO_ITEM] = {slot = TEN.Objects.AmmoType.UZI, weapon = TEN.Objects.ObjID.UZI_ITEM}, 
    [TEN.Objects.ObjID.SHOTGUN_AMMO1_ITEM] = {slot = TEN.Objects.AmmoType.SHOTGUN_NORMAL, weapon = TEN.Objects.ObjID.SHOTGUN_ITEM},
    [TEN.Objects.ObjID.SHOTGUN_AMMO2_ITEM] = {slot = TEN.Objects.AmmoType.SHOTGUN_WIDE, weapon = TEN.Objects.ObjID.SHOTGUN_ITEM},
    [TEN.Objects.ObjID.REVOLVER_AMMO_ITEM] = {slot = TEN.Objects.AmmoType.REVOLVER, weapon = TEN.Objects.ObjID.REVOLVER_ITEM}, 
    [TEN.Objects.ObjID.CROSSBOW_AMMO1_ITEM] = {slot = TEN.Objects.AmmoType.CROSSBOW_BOLT_NORMAL, weapon = TEN.Objects.ObjID.CROSSBOW_ITEM},
    [TEN.Objects.ObjID.CROSSBOW_AMMO2_ITEM] = {slot = TEN.Objects.AmmoType.CROSSBOW_BOLT_POISON, weapon = TEN.Objects.ObjID.CROSSBOW_ITEM},
    [TEN.Objects.ObjID.CROSSBOW_AMMO3_ITEM] = {slot = TEN.Objects.AmmoType.CROSSBOW_BOLT_EXPLOSIVE, weapon = TEN.Objects.ObjID.CROSSBOW_ITEM},
    [TEN.Objects.ObjID.HK_AMMO_ITEM] = {slot = TEN.Objects.AmmoType.HK, weapon = TEN.Objects.ObjID.HK_ITEM},
    [TEN.Objects.ObjID.GRENADE_AMMO1_ITEM] = {slot = TEN.Objects.AmmoType.GRENADE_NORMAL, weapon = TEN.Objects.ObjID.GRENADE_GUN_ITEM},
    [TEN.Objects.ObjID.GRENADE_AMMO2_ITEM] = {slot = TEN.Objects.AmmoType.GRENADE_FRAG, weapon = TEN.Objects.ObjID.GRENADE_GUN_ITEM},
    [TEN.Objects.ObjID.GRENADE_AMMO3_ITEM] = {slot = TEN.Objects.AmmoType.GRENADE_FLASH, weapon = TEN.Objects.ObjID.GRENADE_GUN_ITEM},
    [TEN.Objects.ObjID.HARPOON_AMMO_ITEM] = {slot = TEN.Objects.AmmoType.HARPOON, weapon = TEN.Objects.ObjID.HARPOON_ITEM},
    [TEN.Objects.ObjID.ROCKET_LAUNCHER_AMMO_ITEM] = {slot = TEN.Objects.AmmoType.ROCKET, weapon = TEN.Objects.ObjID.ROCKET_LAUNCHER_ITEM}
}

PICKUP_DATA.HEALTH_SET = {
    [TEN.Objects.ObjID.BIGMEDI_ITEM] = PICKUP_DATA.HEALTH_MAX,
    [TEN.Objects.ObjID.SMALLMEDI_ITEM] = PICKUP_DATA.HEALTH_MAX / 2
}

PICKUP_DATA.ItemActionFlags = {
    {bit = ItemAction.EQUIP, string = "equip"},
    {bit = ItemAction.USE, string = "use"},
    {bit = ItemAction.EXAMINE, string = "examine"},
    {bit = ItemAction.CHOOSE_AMMO_SHOTGUN, string = "choose_ammo"},
    {bit = ItemAction.CHOOSE_AMMO_CROSSBOW, string = "choose_ammo"},
    {bit = ItemAction.CHOOSE_AMMO_GRENADEGUN, string = "choose_ammo"},
    {bit = ItemAction.CHOOSE_AMMO_UZI, string = "choose_ammo"},
    {bit = ItemAction.CHOOSE_AMMO_PISTOLS, string = "choose_ammo"},
    {bit = ItemAction.CHOOSE_AMMO_REVOLVER, string = "choose_ammo"},
    {bit = ItemAction.LOAD, string = "load_game"},
    {bit = ItemAction.SAVE, string = "save_game"},
    {bit = ItemAction.CHOOSE_AMMO_HK, string = "choose_ammo"},
    {bit = ItemAction.STATISTICS , string = "statistics"},
    {bit = ItemAction.CHOOSE_AMMO_HARPOON, string = "choose_ammo"},
    {bit = ItemAction.CHOOSE_AMMO_ROCKET, string = "choose_ammo"},
    {bit = ItemAction.COMBINE, string = "combine"},
    {bit = ItemAction.SEPARATE, string = "separate"},
}

PICKUP_DATA.CHOOSE_AMMO_FLAGS = {
    ItemAction.CHOOSE_AMMO_SHOTGUN,
    ItemAction.CHOOSE_AMMO_CROSSBOW,
    ItemAction.CHOOSE_AMMO_GRENADEGUN,
    ItemAction.CHOOSE_AMMO_UZI,
    ItemAction.CHOOSE_AMMO_PISTOLS,
    ItemAction.CHOOSE_AMMO_REVOLVER,
    ItemAction.CHOOSE_AMMO_HARPOON,
    ItemAction.CHOOSE_AMMO_ROCKET
}

PICKUP_DATA.INVENTORY_MODE = 
{
    INVENTORY = 1,
    RING_OPENING = 2,
    RING_CLOSING = 3,
	RING_CHANGE = 4,
    RING_ROTATE = 5,
    STATISTICS_OPEN = 6,
	STATISTICS = 7,
    STATISTICS_CLOSE = 8,
    EXAMINE_OPEN = 9,
	EXAMINE = 10,
	EXAMINE_RESET = 11,
    EXAMINE_CLOSE = 12,
    ITEM_USE = 13,
    ITEM_SELECT = 14,
    ITEM_DESELECT = 15,
    ITEM_SELECTED = 16,
    COMBINE = 17,
    COMBINE_SETUP = 18,
    COMBINE_CLOSE = 19,
    COMBINE_RING_OPENING = 20,
    COMBINE_SUCCESS = 21,
	COMBINE_COMPLETE = 22,
	SEPARATE = 23,
    SEPARATE_COMPLETE = 24,
    AMMO_SELECT_SETUP = 25,
    AMMO_SELECT_OPEN = 26,
    AMMO_SELECT = 27,
    AMMO_SELECT_CLOSE = 28,
    SAVE_SETUP = 29,
    SAVE_MENU = 30,
    SAVE_CLOSE = 31,
    WEAPON_MODE_SETUP = 32,
    WEAPON_MODE = 33,
    WEAPON_MODE_CLOSE = 34
}

PICKUP_DATA.GetRow = function(lookupValue)
    
	local lookupCol = COL.OBJECT_ID

    for _, row in ipairs(PICKUP_DATA.constants) do
        if row[lookupCol] == lookupValue then
            return row
        end
    end

    return nil
end

PICKUP_DATA.ConvertRowData = function(row)
    return {
        objectID = row[COL.OBJECT_ID],
        yOffset = row[COL.YOFFSET],
        scale = row[COL.SCALE],
        rotation = row[COL.ROTATION],
        menuActions = row[COL.MENUACTIONS],
        name = row[COL.DISPLAY_NAME],
        meshBits = row[COL.MESHBITS],
        orientation = row[COL.ORIENTATION],
		type = row[COL.TYPE],
		combine = row[COL.COMBINE],
		ringName = row[COL.RING],
    }
end

PICKUP_DATA.AMMO_TYPE_TO_OBJECT = {}

for objID, data in pairs(PICKUP_DATA.AMMO_SET) do
    PICKUP_DATA.AMMO_TYPE_TO_OBJECT[data.slot] = objID
end

return PICKUP_DATA